controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Staff ;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],

        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

	    if(!$staff = Staff::find()->all()) {
	        return $this->render('index');
        }else {
		    $model = new Staff() ;
		    return $this->render('structure',['model'=>$model] );// Строим дерево
	    }
    }


	/**
	 * Displays contact page.
	 *
	 * @return string
	 */
	public function actionAddemployee()
	{
		if(Staff::find()->all()) {

			$model = new Staff();

			if ($model->load(Yii::$app->request->post()) && $model->save()) {

				$model->parentname = Staff::getParentName($model->parentid) ;
				$model->save() ;

				return $this->render('addemployeeconfirm', ['model' => $model]);
			} else {

				return $this->render('addemployee', ['model' => $model]); // либо страница отображается первый раз, либо есть ошибка в данных
			}
		}else {
			return $this->render('index');
		}


	}
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionStructure()
    {
	    $model = new Staff() ;
	    return $this->render('structure',['model'=>$model] );// Строим дерево

    }


	public function actionBoss()
	{
		$model = new Staff();
		$model->parentid = -1 ;

		if ($model->load(Yii::$app->request->post())  && $model->save()) {

			return $this->render('bossconfirm', ['model' => $model]);
		} else {

			return $this->render('bossentry', ['model' => $model]); // либо страница отображается первый раз, либо есть ошибка в данных
		}
	}
}

controllers/StaffController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Staff;
use app\models\Staffsearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StaffController implements the CRUD actions for Staff model.
 */
class StaffController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Staff models.
     * @return mixed
     */
    public function actionIndex()
    {
	    if(Staff::find()->all()) {
		    $searchModel = new Staffsearch();
		    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		    return $this->render('index', [
			    'searchModel' => $searchModel,
			    'dataProvider' => $dataProvider,
		    ]);
	    }else {
		   return $this->render('emptylist',['model' => $model,]) ;
	    }
    }

    /**
     * Displays a single Staff model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Staff model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Staff();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Staff model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

	        $model->parentname= Staff::getParentName($model['parentid']);
	        $model->save();

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Staff model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Staff model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Staff the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Staff::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'ZABOTA',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Структура компании', 'url' => ['/site/index']],
            ['label' => 'Список сотрудников', 'url' => ['/staff/index']],
            ['label' => 'Добавить сотрудника', 'url' => ['/site/addemployee']],

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy;<?= date('Y') ?> Забота наша простая, - забота наша такая : жила бы страна родная и нету других забот...&nbsp </p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>